# Project: PALESDL
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++ #-D__DEBUG__
CC   = gcc #-D__DEBUG__
RES  = 
OBJ  =     PALESDL_IO.o PALESDL.o PALESDL_VID.o PALESDL_CONFIG.o PALE48K.o PALEMEM.o PALEROM.o PALE96K.o PALE128K.o  PALE_KEYS.o PALETAPS.o PALERAWTAPE.o  sge_surface.o sge_rotation.o sge_blib.o sge_primitives.o KOGEL/z80.o KOGEL/KOGELMEM.o KOGEL/KOGELIO.o  DOSFONTS.o DOSDIR.o PALEDOS_TEMP.o $(RES)
LINKOBJ  = PALESDL_IO.o PALESDL.o PALESDL_VID.o PALESDL_CONFIG.o PALE48K.o PALEMEM.o PALEROM.o PALE96K.o PALE128K.o  PALE_KEYS.o PALETAPS.o PALERAWTAPE.o  sge_surface.o sge_rotation.o sge_blib.o sge_primitives.o KOGEL/z80.o KOGEL/KOGELMEM.o KOGEL/KOGELIO.o  DOSFONTS.o DOSDIR.o PALEDOS_TEMP.o $(RES)
LIBS =  
INCS =   
BIN  = palesdl.bin
CXXFLAGS = $(CXXINCS)   -fexpensive-optimizations -O3 -pg -g3
CFLAGS = $(INCS) -W -fno-exceptions -g -O0  -fexpensive-optimizations -O3 -pg -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before palesdl.bin all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "palesdl.bin" $(LIBS) -lSDL

PALESDL_IO.o: PALESDL_IO.C
	$(CPP) -c PALESDL_IO.C -o PALESDL_IO.o $(CXXFLAGS)

PALESDL.o: PALESDL.C
	$(CPP) -c PALESDL.C -o PALESDL.o $(CXXFLAGS)

PALESDL_CONFIG.o: PALESDL_CONFIG.C
	$(CPP) -c PALESDL_CONFIG.C -o PALESDL_CONFIG.o $(CXXFLAGS)

PALEMEM.o: PALEMEM.C
	$(CPP) -c PALEMEM.C -o PALEMEM.o $(CXXFLAGS)

PALEROM.o: PALEROM.C
	$(CPP) -c PALEROM.C -o PALEROM.o $(CXXFLAGS)

PALE96K.o: PALE96K.C
	$(CPP) -c PALE96K.C -o PALE96K.o $(CXXFLAGS)

PALE48K.o: PALE48K.C
	$(CPP) -c PALE48K.C -o PALE48K.o $(CXXFLAGS)

PALE128K.o: PALE128K.C
	$(CPP) -c PALE128K.C -o PALE128K.o $(CXXFLAGS)

PALE_KEYS.o: PALE_KEYS.C
	$(CPP) -c PALE_KEYS.C -o PALE_KEYS.o $(CXXFLAGS)

PALETAPS.o: PALETAPS.C
	$(CPP) -c PALETAPS.C -o PALETAPS.o $(CXXFLAGS)

PALEDISK.o: PALEDISK.C
	$(CPP) -c PALEDISK.C -o PALEDISK.o $(CXXFLAGS)

PALERAWTAPE.o: PALERAWTAPE.C
	$(CPP) -c PALERAWTAPE.C -o PALERAWTAPE.o $(CXXFLAGS)

KOGEL/z80.o: KOGEL/z80.c
	$(CPP) -c KOGEL/z80.c -o KOGEL/z80.o $(CXXFLAGS)

KOGEL/KOGELMEM.o: KOGEL/KOGELMEM.C
	$(CPP) -c KOGEL/KOGELMEM.C -o KOGEL/KOGELMEM.o $(CXXFLAGS)

KOGEL/KOGELIO.o: KOGEL/KOGELIO.C
	$(CPP) -c KOGEL/KOGELIO.C -o KOGEL/KOGELIO.o $(CXXFLAGS)

PALEDOS_TEMP.o: PALEDOS_TEMP.C
	$(CPP) -c PALEDOS_TEMP.C -o PALEDOS_TEMP.o $(CXXFLAGS)

DOSFONTS.o: DOSFONTS.C
	$(CPP) -c DOSFONTS.C -o DOSFONTS.o $(CXXFLAGS)

DOSDIR.o: DOSDIR.c
	$(CPP) -c DOSDIR.c -o DOSDIR.o $(CXXFLAGS)

PALESDL_VID.o: PALESDL_VID.C
	$(CPP) -c PALESDL_VID.C -o PALESDL_VID.o $(CXXFLAGS)
